name: Reproducible Build

on:
  push:
    # branches: [main]
    # paths:
    #   - 'cmd/rep-build/**'
  workflow_dispatch:

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.6'

      #TODO: automatically scan the leaf nodes of the dependency graph for generator.go files instead of hardcoding the path
      - name: Generate Containerfiles
        run: |
          go run npmjs/svelte/5.48.2/generator.go

      - name: Build Container Images
        run: |
          podman build -f npmjs/svelte/5.48.2/Containerfile \
          -t svelte:5.48.2 .

      - name: Run reproducibility checks
        run: |
          set -e
          podman run --rm --name svelte-test svelte:5.48.2

      - name: Extract build artifacts
        run: |
          podman create --name extract svelte:5.48.2
          podman cp extract:tmp/build.tgz ./svelte-5.48.2.tgz
          podman rm extract

      - name: Upload built artifact
        uses : actions/upload-artifact@v6
        with:
          name: svelte-5.48.2-build
          path: svelte-5.48.2.tgz
